#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : xkill
Version  : 1.0.5
Release  : 1
URL      : https://www.x.org/releases/individual/app/xkill-1.0.5.tar.gz
Source0  : https://www.x.org/releases/individual/app/xkill-1.0.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xkill-bin = %{version}-%{release}
Requires: xkill-license = %{version}-%{release}
Requires: xkill-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xkill is a utility for forcing the X server to close connections to
clients.  This program is very dangerous, but is useful for aborting
programs that have displayed undesired windows on a user's screen.

%package bin
Summary: bin components for the xkill package.
Group: Binaries
Requires: xkill-license = %{version}-%{release}
Requires: xkill-man = %{version}-%{release}

%description bin
bin components for the xkill package.


%package license
Summary: license components for the xkill package.
Group: Default

%description license
license components for the xkill package.


%package man
Summary: man components for the xkill package.
Group: Default

%description man
man components for the xkill package.


%prep
%setup -q -n xkill-1.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550612101
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1550612101
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xkill
cp COPYING %{buildroot}/usr/share/package-licenses/xkill/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xkill

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xkill/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xkill.1
