#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : xkill
Version  : 1.0.5
Release  : 3
URL      : https://www.x.org/releases/individual/app/xkill-1.0.5.tar.gz
Source0  : https://www.x.org/releases/individual/app/xkill-1.0.5.tar.gz
Source1  : https://www.x.org/releases/individual/app/xkill-1.0.5.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT-Opengroup
Requires: xkill-bin = %{version}-%{release}
Requires: xkill-license = %{version}-%{release}
Requires: xkill-man = %{version}-%{release}
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xmuu)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xproto)

%description
xkill is a utility for forcing the X server to close connections to
clients.  This program is very dangerous, but is useful for aborting
programs that have displayed undesired windows on a user's screen.

%package bin
Summary: bin components for the xkill package.
Group: Binaries
Requires: xkill-license = %{version}-%{release}

%description bin
bin components for the xkill package.


%package license
Summary: license components for the xkill package.
Group: Default

%description license
license components for the xkill package.


%package man
Summary: man components for the xkill package.
Group: Default

%description man
man components for the xkill package.


%prep
%setup -q -n xkill-1.0.5
cd %{_builddir}/xkill-1.0.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604598947
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1604598947
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xkill
cp %{_builddir}/xkill-1.0.5/COPYING %{buildroot}/usr/share/package-licenses/xkill/8dd1a5611e7e942c1cb89e33c1f4667e60b5314f
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xkill

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xkill/8dd1a5611e7e942c1cb89e33c1f4667e60b5314f

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xkill.1
